### ISSUE TITLE
BUG: Failure in sign in with Google

### ISSUE THREAD

**Issue by avibathula** [leandroercoli/SaasterKit#5]
Hi - just followed your instructions and didn't do much. Within Clerk I enabled Google authentication in Clerk and the initial website opened up properly. HURRAY!!!! 👍 

When I attempted to sign in, Clerk took me through the google auth and then I see "Dashboard" button instead of text link asking me to sign in - seem to be second HURRAY!!!! 👍 👍 

When I click on "Dashboard" - I am seeing 

```
 GET / 200 in 935ms
 ○ Compiling /[locale]/dashboard ...
 ✓ Compiled /[locale]/dashboard in 1672ms (4778 modules)
 GET /dashboard?_rsc=14foe 200 in 6507ms
 ⨯ src/libs/database/utils.ts (38:22) @ getSignedInUserOrThrow
 ⨯ Error: User not signed in
    at getSignedInUserOrThrow (./src/libs/database/utils.ts:37:22)
    at async getUserRecentTodoItems (./src/libs/database/functions/todo/getUserRecentTodoItems.ts:14:26)
    at async Dashboard (dashboard/page.tsx:17:29)
digest: "2725572128"
  36 | export async function getSignedInUserOrThrow(include?: Prisma.UserInclude) {
  37 |     const user = await getSignedInUser(include);
> 38 |     if (!user) throw new Error('User not signed in');
     |                      ^
  39 |
  40 |     return user;
  41 | }
```

and the UI is showing "Something is wrong" .... NOT HURRAY 👎 👎 👎

**Comment by brycebayens** [comment]
Same!
